#!/bin/sh
### BEGIN INIT INFO
# Provides:          bluesky-module
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: skyblue-module with RaspberryPI(s) sensors and actuator controller extensible modules
### END INIT INFO

case "$1" in
start)
 currPath=${PWD}
 cd /skyblue/GPIO-GainerSerial-modules
 sudo su -c "nohup ./run.sh >> /dev/null 2>&1 &"
 #sudo nohup ./run.sh >> /dev/null 2>&1 &
 #sudo su -c "./run.sh & >&2"
 cd $currPath
 echo "INFO: skyblue other modules started." >&2
    ;;
stop)
        BLUESKY_PID=`ps ax | grep GainerTestJava | awk '{print $1}'`
#        echo $BLUESKY_PID
        arr=`echo $BLUESKY_PID`
#        echo $arr
        for i in $arr ; do
#               echo $i
                su -c "kill $i &> /dev/null"
        done
	echo "INFO: skyblue other modules stopped." >&2
    ;;

restart)
    $0 stop
    $0 start
    ;;
*)
    echo "usage: $0 (start|stop|restart)"
;;
esac
